// app.js
export const LOGOUT = 'LOGOUT'
export const SAVE_TOKEN = 'SAVE_TOKEN'
export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
export const UPDATE_USER = 'UPDATE_USER'

export const UPDATE_TITLE = 'UPDATE_TITLE'

export const IS_LOADING = 'IS_LOADING'
export const FINISHED_LOADING = 'FINISHED_LOADING'

export const SIDEBAR_COLLAPSED = 'SIDEBAR_COLLAPSED'
export const SIDEBAR_VISIBLE = 'SIDEBAR_VISIBLE'